// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// CategoryHandler is an autogenerated mock type for the CategoryHandler type
type CategoryHandler struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: c
func (_m *CategoryHandler) FindAll(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewCategoryHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewCategoryHandler creates a new instance of CategoryHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCategoryHandler(t mockConstructorTestingTNewCategoryHandler) *CategoryHandler {
	mock := &CategoryHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
