// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	model "git.garena.com/sea-labs-id/batch-01/rafly-nagachi/final-project-backend/model"
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// DeliveryRepository is an autogenerated mock type for the DeliveryRepository type
type DeliveryRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: tx, d
func (_m *DeliveryRepository) Create(tx *gorm.DB, d *model.Delivery) (*model.Delivery, error) {
	ret := _m.Called(tx, d)

	var r0 *model.Delivery
	if rf, ok := ret.Get(0).(func(*gorm.DB, *model.Delivery) *model.Delivery); ok {
		r0 = rf(tx, d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Delivery)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gorm.DB, *model.Delivery) error); ok {
		r1 = rf(tx, d)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: tx
func (_m *DeliveryRepository) FindAll(tx *gorm.DB) ([]*model.Delivery, error) {
	ret := _m.Called(tx)

	var r0 []*model.Delivery
	if rf, ok := ret.Get(0).(func(*gorm.DB) []*model.Delivery); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Delivery)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gorm.DB) error); ok {
		r1 = rf(tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: tx, id
func (_m *DeliveryRepository) FindByID(tx *gorm.DB, id uint) (*model.Delivery, error) {
	ret := _m.Called(tx, id)

	var r0 *model.Delivery
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint) *model.Delivery); ok {
		r0 = rf(tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Delivery)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gorm.DB, uint) error); ok {
		r1 = rf(tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: tx, id, d
func (_m *DeliveryRepository) Update(tx *gorm.DB, id uint, d *model.Delivery) (*model.Delivery, error) {
	ret := _m.Called(tx, id, d)

	var r0 *model.Delivery
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint, *model.Delivery) *model.Delivery); ok {
		r0 = rf(tx, id, d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Delivery)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gorm.DB, uint, *model.Delivery) error); ok {
		r1 = rf(tx, id, d)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewDeliveryRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeliveryRepository creates a new instance of DeliveryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeliveryRepository(t mockConstructorTestingTNewDeliveryRepository) *DeliveryRepository {
	mock := &DeliveryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
