// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// GameHandler is an autogenerated mock type for the GameHandler type
type GameHandler struct {
	mock.Mock
}

// AddCouponPrizeToUser provides a mock function with given fields: c
func (_m *GameHandler) AddCouponPrizeToUser(c *gin.Context) {
	_m.Called(c)
}

// FindAll provides a mock function with given fields: c
func (_m *GameHandler) FindAll(c *gin.Context) {
	_m.Called(c)
}

// FindByUserID provides a mock function with given fields: c
func (_m *GameHandler) FindByUserID(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewGameHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewGameHandler creates a new instance of GameHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGameHandler(t mockConstructorTestingTNewGameHandler) *GameHandler {
	mock := &GameHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
