// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// OrderItemHandler is an autogenerated mock type for the OrderItemHandler type
type OrderItemHandler struct {
	mock.Mock
}

// CreateOrderItem provides a mock function with given fields: c
func (_m *OrderItemHandler) CreateOrderItem(c *gin.Context) {
	_m.Called(c)
}

// DeleteOrderItemByID provides a mock function with given fields: c
func (_m *OrderItemHandler) DeleteOrderItemByID(c *gin.Context) {
	_m.Called(c)
}

// FindOrderItemByUserID provides a mock function with given fields: c
func (_m *OrderItemHandler) FindOrderItemByUserID(c *gin.Context) {
	_m.Called(c)
}

// UpdateOrderItemByID provides a mock function with given fields: c
func (_m *OrderItemHandler) UpdateOrderItemByID(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewOrderItemHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrderItemHandler creates a new instance of OrderItemHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrderItemHandler(t mockConstructorTestingTNewOrderItemHandler) *OrderItemHandler {
	mock := &OrderItemHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
