// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// PaymentOptionHandler is an autogenerated mock type for the PaymentOptionHandler type
type PaymentOptionHandler struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: c
func (_m *PaymentOptionHandler) FindAll(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewPaymentOptionHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewPaymentOptionHandler creates a new instance of PaymentOptionHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPaymentOptionHandler(t mockConstructorTestingTNewPaymentOptionHandler) *PaymentOptionHandler {
	mock := &PaymentOptionHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
