// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// ReviewHandler is an autogenerated mock type for the ReviewHandler type
type ReviewHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: c
func (_m *ReviewHandler) Create(c *gin.Context) {
	_m.Called(c)
}

// FindByMenuID provides a mock function with given fields: c
func (_m *ReviewHandler) FindByMenuID(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewReviewHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewReviewHandler creates a new instance of ReviewHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReviewHandler(t mockConstructorTestingTNewReviewHandler) *ReviewHandler {
	mock := &ReviewHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
