// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	model "git.garena.com/sea-labs-id/batch-01/rafly-nagachi/final-project-backend/model"
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: tx, user
func (_m *UserRepository) Create(tx *gorm.DB, user *model.User) (*model.User, error) {
	ret := _m.Called(tx, user)

	var r0 *model.User
	if rf, ok := ret.Get(0).(func(*gorm.DB, *model.User) *model.User); ok {
		r0 = rf(tx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gorm.DB, *model.User) error); ok {
		r1 = rf(tx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByEmail provides a mock function with given fields: tx, email
func (_m *UserRepository) FindByEmail(tx *gorm.DB, email string) (*model.User, error) {
	ret := _m.Called(tx, email)

	var r0 *model.User
	if rf, ok := ret.Get(0).(func(*gorm.DB, string) *model.User); ok {
		r0 = rf(tx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gorm.DB, string) error); ok {
		r1 = rf(tx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: tx, id
func (_m *UserRepository) FindByID(tx *gorm.DB, id uint) (*model.User, error) {
	ret := _m.Called(tx, id)

	var r0 *model.User
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint) *model.User); ok {
		r0 = rf(tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gorm.DB, uint) error); ok {
		r1 = rf(tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByIDWithCoupons provides a mock function with given fields: tx, id
func (_m *UserRepository) FindByIDWithCoupons(tx *gorm.DB, id uint) (*model.User, error) {
	ret := _m.Called(tx, id)

	var r0 *model.User
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint) *model.User); ok {
		r0 = rf(tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gorm.DB, uint) error); ok {
		r1 = rf(tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: tx, id, user
func (_m *UserRepository) Update(tx *gorm.DB, id uint, user *model.User) (*model.User, error) {
	ret := _m.Called(tx, id, user)

	var r0 *model.User
	if rf, ok := ret.Get(0).(func(*gorm.DB, uint, *model.User) *model.User); ok {
		r0 = rf(tx, id, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gorm.DB, uint, *model.User) error); ok {
		r1 = rf(tx, id, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRepository(t mockConstructorTestingTNewUserRepository) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
